import { TicketFieldColumn } from 'indiedesk-common-lib';

export const ticketColumns: TicketFieldColumn[] = [
  {
    id: 'id',
    header: 'Ticket ID',
    type: 'text',
    isRequired: true,
    isVisible: true,
    readonly: true,
  },
  {
    id: 'title',
    header: 'Title',
    type: 'text',
    isRequired: true,
    isVisible: true,
    readonly: false,
  },
  {
    id: 'assignee',
    header: 'Assignee',
    type: 'text',
    isRequired: false,
    isVisible: true,
    readonly: false,
  },
  {
    id: 'project.name',
    header: 'Project',
    type: 'text',
    isRequired: true,
    isVisible: true,
    readonly: true,
  },
  {
    id: 'project.client.name',
    header: 'Client',
    type: 'string',
    isRequired: true,
    isVisible: true,
    readonly: true,
  },
  {
    id: 'status',
    header: 'Status',
    type: 'code',
    isRequired: true,
    isVisible: true,
    readonly: false,
    options: [
      { label: 'Open', value: 'OPEN' },
      { label: 'In Progress', value: 'IN_PROGRESS' },
      { label: 'Done', value: 'DONE' },
      { label: 'Cancelled', value: 'CANCELLED' },
    ],
  },
  {
    id: 'priority',
    header: 'Priority',
    type: 'code',
    isRequired: true,
    isVisible: true,
    readonly: false,
    options: [
      { label: 'Low', value: 'LOW' },
      { label: 'Medium', value: 'MEDIUM' },
      { label: 'High', value: 'HIGH' },
      { label: 'Critical', value: 'CRITICAL' },
    ],
  },
  {
    id: 'description',
    header: 'Description',
    type: 'textarea',
    isVisible: true,
    isRequired: false,
    readonly: false,
  },
  {
    id: 'createdAt',
    header: 'Created At',
    type: 'date',
    isVisible: true,
    isRequired: false,
    readonly: true,
  },
  {
    id: 'updatedAt',
    header: 'Updated At',
    type: 'date',
    isVisible: true,
    isRequired: false,
    readonly: true,
  },
];
