on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy the UI'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - 'modules/ui/**'
      - 'modules/common/**'
      - '.github/workflows/ui-workflow.yaml'

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/ui
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: '10.8.1'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Install dependencies of common lib
        run: pnpm install
        working-directory: modules/common

      - name: Install dependencies of ui
        run: pnpm install
        working-directory: modules/ui

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test:ci

      - name: Deploy
        if: contains(github.event.head_commit.message, '[DEPLOY]')
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy modules/ui/dist/browser --project-name=indie-desk