on:
  push:
    branches:
      - main
    paths:
      - 'modules/ui/**'
jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/ui
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:ci
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy modules/ui/dist --project-name=indie-desk